services:
  - type: web
    name: emailbulk-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=3 --bind=0.0.0.0:$PORT"
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: emailbulk-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SES_CONFIGURATION_SET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SCHEDULER_ENABLED
        value: "true"

databases:
  - name: emailbulk-db
    ipAllowList: []  # allow connections from everywhere
    plan: free
